import collections

def main():
    dq=collections.deque()
    dq.append(1)
    dq.append(2)
    print(dq)
    dq.appendleft(10)
    print(dq)
    dq.append(20)
    print(dq)
    dq.pop()
    print(dq)
    dq.popleft()
    print(dq)
    dq.append(5)
    dq.appendleft(100)
    print(dq.index(5,0,7))
    print(dq.count(5))
    dq.extend([10,11,12])
    print(dq)
    dq.extendleft([40,50,60])
    print(dq)
    dq.reverse()
    print(dq)
    dq.rotate(3)
    print(dq)
    dq.rotate(-4)
    print(dq)
main()
